config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: [:index] do
    resources :bookmarks
  end
  resources :bookmarks, only: [ :new, :create, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: [:list_id] }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-6">
      <h2>Add a new bookmark</h2>
      <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie %>
      <%= f.association :list %>
      <%= f.input :comment, placeholder: 'Say something about this movie!' %>
      <%= f.button :submit, class: "btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render 'partials/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render 'partials/hero' %>
<div class="container mt-3 mb-3">
  <div class="row">
    <div class="col-10">
      <h1>My Lists</h1>
    </div>
    <div class="col-2">
      <a href=" <%= new_list_path %> " class="btn btn-primary">Create a movie list</a>
    </div>
  </div>
  <div class="row">
    <% @lists.each do |list| %>
      <a class="text-decoration-none" href=" <%= list_url(list) %> ">
      <% if list.photo.attached? %>
        <div class="col-4 mt-3 card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path list.photo.key, height: 300, crop: :fill %>');">
          <%= list.name %>
        </div>
      <% else %>
        <div class="col-4 mt-3 card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('classic.jpg');">
          <%= list.name %>
        </div>
      <% end %>
      </a>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container mt-3">
  <div class="row justify-content-center">
    <div class="col-6">
    <h2>Create a new list:</h2>
    <%= simple_form_for @list do |f| %>
    <%= f.input :photo, as: :file %>
    <%= f.input :name, placeholder: 'Name your list' %>
    <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<%= render 'partials/banner' %>
<div class="container mt-3">
  <div class="row">
    <div class="d-flex flex-row-reverse">
      <div class="p-2">
        <%= link_to 'Delete this list', list_path(@list), method: :delete, data: { confirm: "Are you sure"}, class: 'btn btn-danger' %>
      </div>
      <div class="p-2">
        <%= link_to "Add a movie", new_list_bookmark_path(@list), class:"btn btn-success" %>
      </div>
    </div>
  </div>
  <div class="row">
    <% @list.bookmarks.each do |bookmark| %>
    <div class="col-md-3 mt-3">
      <div class="card" style="width: 36rem;">
        <img class="card-img-top" src=" <%= bookmark.movie.poster_url %> " alt="Movie poster">
        <div class="card-body">
          <h5 class="card-title"><%= bookmark.movie.title %> | <%= bookmark.movie.rating %> ⭐️ </h5>
          <p class="card-text"><%= bookmark.movie.overview %></p>
        </div>
        <div class="card-body d-flex">
          <div class="p-2">
            <%= bookmark.comment %>
          </div>
          <div class="p-2">
            <%= link_to 'delete', bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure"}, class: 'text-danger card-link' %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

</div>

app/views/partials/_banner.html.erb
<% if @list.photo.attached? %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>');">
    <div class="container">
      <h1><%= @list.name %> Movies</h1>
    </div>
  </div>
<% else %>
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('classic.jpg');">
    <div class="container">
      <h1><%= @list.name %> Movies</h1>
    </div>
  </div>
<% end %>

app/views/partials/_hero.html.erb
<div class="px-4 py-5 text-center banner hero">
  <h1>Films List</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">Create custom film lists</p>
    <p class="lead mb-4">Curate your very own selection</p>
  </div>
</div>

app/views/partials/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
            <%# <%= image_tag 'popcorn_img' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My Lists", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", new_list_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>